### ISSUE TITLE
Please add readme

### ISSUE THREAD

**Issue by andig** [baswenneker/pimatic-ifttt#1]
... On how to use this plugin? Thanks!

**Comment by baswenneker** [comment]
Hi andig,

I added the README. Let me know if you have questions.

Cheers, Bas

**Comment by andig** [comment]
Excellent, thanks!

**Comment by baswenneker** [comment]
Fyi, I've just published an updated version of pimatic-ifttt to NPM. Just run `nom update` from the pimatic root directory to update the plugin.

**Comment by andig** [comment]
Thank you, highly appreciated.
