### ISSUE TITLE
Detach your fork from pimatic-plugin-template and turn it into a standalone repository

### ISSUE THREAD

**Issue by mwittig** [baswenneker/pimatic-ifttt#5]
Please detach your fork from pimatic-plugin-template and turn it into a standalone repository

Why this should be done:
- Have a look at the history! It is not the your the history of your project, but the history of the plugin-template project. This is confusing.
- If I have a fork of another pimatic project which has not been detached either I cannot fork your project as both projects are recognized as pimatic-plugin-template projects. That's bad!

See also http://stackoverflow.com/a/16052845/4816693 on the matter and how to detach the fork

It is really an issue as there currently also other pimatic project with the same issue. See also
https://github.com/DheerajKhajuria/pimatic-mysensors/issues/45

**Comment by baswenneker** [comment]
Hi Marcus,

I'll ask Github Support to detach the fork.

**Comment by mwittig** [comment]
Hi Bas, 

That's great! Thanks

**Comment by mwittig** [comment]
Apparently, this has be done already. So I am closing issue this now.
